version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports: 
      - 27017:27017
  node:
    image: web
    build: myapp
    environment: 
      MONGOURL: mongodb://mongodb:27017
      REDISURL: redis://redis:6379
    depends_on: 
      - mongodb
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  nginx:
    build: nginx
    ports:
    - 8080:80
    environment:
    - HOST=node